line-length = 100
target-version = "py311"
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # isort
  "UP",  # pyupgrade
  "N",   # pep8-naming
]
ignore = [
]

[format]
quote-style = "double"
indent-style = "space"

