name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-test:
    name: lint+type+test (${{ matrix.os }} / py${{ matrix.python }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python: ["3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies (dev)
        run: |
          pip install -e .[dev]
        env:
          PIP_DISABLE_PIP_VERSION_CHECK: "1"

      - name: Lint (ruff)
        run: ruff check .

      - name: Format (black --check)
        run: black --check .

      - name: Type check (mypy)
        run: mypy .

      - name: Run tests (pytest + coverage)
        env:
          # Guardrails to avoid network usage; code should not depend on network.
          NO_NETWORK: "1"
        run: |
          pytest -q

